CREATE TABLE IF NOT EXISTS obras (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome_obra VARCHAR(255) NOT NULL,
    ano INTEGER NOT NULL,
    autor VARCHAR(255) NOT NULL,
    museu VARCHAR(255) NOT NULL,
    arquivo_nome VARCHAR(255),
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
